/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema1.h"

bool_t
xdr_request_access_params (XDR *xdrs, request_access_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->request_token, ~0))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->automatic_refresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_result (XDR *xdrs, request_access_result *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error_message, ~0))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->has_errors))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_action_params (XDR *xdrs, validate_action_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->operation, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_action_result (XDR *xdrs, validate_action_result *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->result, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->new_access_token, ~0))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->access_token_refreshed))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_request_result (XDR *xdrs, approve_request_result *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->request_token, ~0))
		 return FALSE;
	 if (!xdr_u_char (xdrs, &objp->signed_token))
		 return FALSE;
	return TRUE;
}
