/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema1.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include "structs.h"
#include "sc_map.h"
#include "sc_array.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
tema1_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *request_authorization_1_arg;
		struct request_access_params request_access_token_1_arg;
		struct validate_action_params validate_delegated_action_1_arg;
		char *approve_request_token_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REQUEST_AUTHORIZATION:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) request_authorization_1_svc;
		break;

	case REQUEST_ACCESS_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_request_access_params;
		_xdr_result = (xdrproc_t) xdr_request_access_result;
		local = (char *(*)(char *, struct svc_req *)) request_access_token_1_svc;
		break;

	case VALIDATE_DELEGATED_ACTION:
		_xdr_argument = (xdrproc_t) xdr_validate_action_params;
		_xdr_result = (xdrproc_t) xdr_validate_action_result;
		local = (char *(*)(char *, struct svc_req *)) validate_delegated_action_1_svc;
		break;

	case APPROVE_REQUEST_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_approve_request_result;
		local = (char *(*)(char *, struct svc_req *)) approve_request_token_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

struct sc_map_sv client_map;
struct sc_map_str access_token_to_name;
struct sc_array_str approvals;
struct sc_array_str resources;
int max_token_duration = 0;
int approvals_pointer = 0;

void init_server(int argc, char** argv) {
	FILE* fp;
	int num_clients;
	int num_resources;

	setvbuf(stdout, NULL, _IONBF, 0);

	sc_map_init_str(&access_token_to_name, 0, 0);

	sc_map_init_sv(&client_map, 0, 0);

	fp = fopen(argv[1], READ_ONLY);
	fscanf(fp, "%d", &num_clients);
	for (int i = 0;  i < num_clients; i++) {
		client_data* data = calloc(sizeof(client_data), 1);
		char* name = calloc(sizeof(char), VARIOUS_TOKENS_LEN + 1);
		
		fscanf(fp, "%s", name);
		data->name = strdup(name);
		sc_map_init_str(&data->permissions, 0, 0);
		sc_map_put_sv(&client_map, name, data);
	}

	sc_array_init(&approvals);
	fp = fopen(argv[2], READ_ONLY);
	for (int i = 0;  i < num_clients; i++) {
		char* line = calloc(sizeof(char), LINE_SIZE);
		fgets(line, LINE_SIZE, fp);
		line[strlen(line) - 1] = '\0';
		sc_array_add(&approvals, line);
	}

	sc_array_init(&resources);
	fp = fopen(argv[3], READ_ONLY);
	fscanf(fp, "%d", &num_resources);
	for (int i = 0;  i < num_resources; i++) {
		char* resource = calloc(sizeof(char), 50);
		fscanf(fp, "%s", resource);
		sc_array_add(&resources, resource);
	}

	fp = fopen(argv[4], READ_ONLY);
	fscanf(fp, "%d", &max_token_duration);
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (TEMA1_PROG, TEMA1_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TEMA1_PROG, TEMA1_VERS, tema1_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TEMA1_PROG, TEMA1_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TEMA1_PROG, TEMA1_VERS, tema1_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TEMA1_PROG, TEMA1_VERS, tcp).");
		exit(1);
	}

	init_server(argc, argv);

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
